CREATE DATABASE IF NOT EXISTS FINANCIAL
COMMENT 'NYSE DATA'
WITH DBPROPERTIES('CREATOR'='BABU','DATE'='12-02-2014');

CREATE TABLE IF NOT EXISTS FINANCIAL.STOCK_EXCHANGE
(
EXCHANGE STRING COMMENT 'COUNTRY CODE',
STOCK_SYMBOL STRING COMMENT 'COMPANY NAME',
STOCK_DATE STRING COMMENT 'DATE',
STOCK_PRICE_OPEN DOUBLE COMMENT 'OPENING PRICE',
STOCK_PRICE_HIGH DOUBLE COMMENT 'HIGH PRICE',
STOCK_PRICE_LOW DOUBLE COMMENT 'LOW PRICE',
STOCK_PRICE_CLOSE DOUBLE COMMENT 'CLOSE PRICE',
STOCK_PRICE_VOLUME DOUBLE COMMENT 'VOLUME PRICE',
STOCK_PRICE_ADJ_CLOSE DOUBLE COMMENT 'ADJ_CLOSE PRICE')
ROW FORMAT DELIMITED FIELDS TERMINATED BY ',';

CREATE TABLE IF NOT EXISTS FINANCIAL.STOCK_EXCHANGEDIVID
(
EXCHANGE STRING COMMENT 'COUNTRY CODE',
STOCK_SYMBOL STRING COMMENT 'COMPANY NAME',
STOCK_DATE STRING COMMENT 'DATE',
STOCK_PRICE_DIVID DOUBLE COMMENT 'OPENING PRICE'
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY ',';
use financial;
CREATE INDEX STOCK_EXCHANGE
ON TABLE STOCK_EXCHANGE (STOCK_DATE)
AS 'org.apache.hadoop.hive.ql.index.compact.CompactIndexHandler'
WITH DEFERRED REBUILD
IDXPROPERTIES ('creator' = 'me', 'created_at' = 'some_time');

